// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Database_First2.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Database_First2.Context
{
    public partial interface INORTHWNDContextProcedures
    {
        Task<List<SalesByCategoryResult>> SalesByCategoryAsync(string CategoryName, string OrdYear, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
